name: gemma_concept_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  
  # Core ML and Deep Learning
  - pytorch>=2.1.0
  - torchvision
  - torchaudio
  
  # Data Science and Numerical Computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Progress bars and utilities
  - tqdm>=4.65.0
  
  # Jupyter notebook support
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=7.0.0
  
  # Additional dependencies via pip
  - pip:
    - transformers>=4.40.0
    - accelerate>=0.28.0
    - sentencepiece>=0.1.99
    - protobuf>=4.21.0
    - huggingface-hub>=0.20.0
    - typing-extensions>=4.5.0
    - datasets>=2.14.0
    - safetensors>=0.4.0
