name: gemma_concept_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  
  # Core ML and Deep Learning (Apple Silicon optimized)
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  
  # Data Science and Numerical Computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Progress bars and utilities
  - tqdm>=4.62.0
  
  # Jupyter notebook support
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # Additional dependencies via pip
  - pip:
    - transformers>=4.35.0
    - accelerate>=0.20.0
    - sentencepiece>=0.1.97
    - protobuf>=3.20.0
    - huggingface-hub>=0.16.0
